Slac22 146 int article hero
SLAC/W6-D9 pull request #303
Opened 2022-08-15 19:49 UTC by dstumberger

2022-08-16 17:38 UTC, kmonahan requested changes
One change needed to the responsive image configuration and one question.

2022-08-16 17:38 UTC, kmonahan commented on config/sync/responsive_image.styles.hero.yml
> +      sizes: '(min-width: 80em) 2880px, 100vw'
This doesn't look right to me. It says that when the browser is at least 1280px wide, the image will be 2880px wide. But it won't be -- it will be 1280px wide. Please adjust either the media query or the size to be accurate, depending on what you intended here.

2022-08-16 17:38 UTC, kmonahan commented on web/themes/gesso/templates/paragraph/paragraph--article-hero.html.twig
> +  {{- hero_credit|raw -}}
I thought value in the preprocess function above gave you the raw value rather than a render array, in which case using `|raw` here as well suggests to me that the content is never getting escaped, which seems dangerous. Am I misreading something?

2022-08-17 18:50 UTC, dstumberger commented on config/sync/responsive_image.styles.hero.yml
> +      sizes: '(min-width: 80em) 2880px, 100vw'
Changed size to '100vw' based on conversation with FED lead.

2022-08-17 18:51 UTC, dstumberger commented on web/themes/gesso/templates/paragraph/paragraph--article-hero.html.twig
> +  {{- hero_credit|raw -}}
removed |raw from the template and instead using ->view() to escape the text in the paragraph preprocess

2022-08-17 19:22 UTC, merged